### ISSUE TITLE
R-CMD Check : selectLongestDuplicate, plotEstimatedWallTimes, removeTails, condenseRepeatedDomains, plotStackedLineage

### ISSUE THREAD

**Issue by Klangina** [JRaviLab/MolEvolvR#114]
- [ ] ~pick_longer_duplicate~ selectLongestDuplicate: no visible binding for global variable ‘AccNum’
- [ ] ~pick_longer_duplicate~ selectLongestDuplicate: no visible binding for global variable ‘row.orig’
- [ ] ~plot_estimated_walltimes~ plotEstimatedWallTimes: get_powerset : <anonymous>: no visible global function definition for ‘combn’
- [ ] ~plot_estimated_walltimes~ plotEstimatedWallTimes: no visible binding for global variable ‘n_inputs’
- [ ] ~plot_estimated_walltimes~ plotEstimatedWallTimes: no visible binding for global variable ‘est_walltime’
- [ ] ~plot_estimated_walltimes~ plotEstimatedWallTimes: no visible binding for global variable ‘advanced_opts’
- [ ] ~remove_tails~ removeTails: no visible binding for global variable ‘domains_keep’
- [ ] ~repeat2s~ condenseRepeatedDomains : no visible binding for global variable ‘.’
- [ ] ~stacked_lin_plot~ plotStackedLineage: no visible binding for global variable ‘cpcols’
- [ ] ~stacked_lin_plot~ plotStackedLineage : no visible global function definition for ‘unit’

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/4#issuecomment-2395224917_

**Comment by Klangina** [comment]
Fixed all the warnings except:

removeTails: no visible binding for global variable ‘domains_keep’
 @jananiravi @the-mayer : Need the logic for extracting domains_keep from prot, kindly guide.

**Comment by the-mayer** [comment]
As the `keep_domains` param defaults to FALSE, it seems like this bit of code rarely (if ever) gets evaluated. Regardless, this is a good find! I'm going to convert your comment to another issue, while merging the other changes in your PR.
