### ISSUE TITLE
[New analysis] Genomic contexts

### ISSUE THREAD

**Issue by jananiravi** [JRaviLab/MolEvolvR#13]
# Genomic context aka neighborhood analyses
- [ ] `edirect` and `eutils` to fetch genes of interest (from a list)
   - [ ] + slurm
- [ ] user-input: no. of neighbors on each side (default: ±7)
- [ ] user-input: filter by intergenic distance (200bp)
- [ ] identify orientation of genes
- [ ] back to tab-delim format with `<- || ->` | `A -> B -> C||<- D`
- [ ] option: indicate query with * or some other marker
- [ ] first: append final GC column to the BLAST output file
- [ ] add DA for each of the neighbors' accessions
- [ ] finally: replace with GC column above with DA+GC `A+B -> C+D`

## Existing tools/papers
- [ ] `rentrez`: [CRAN tutorial](https://cran.r-project.org/web/packages/rentrez/vignettes/rentrez_tutorial.html)
- [ ] Is there a way to retain intergenic distance | to use later as edge weight in networks | Check 2020 PLoSCompBio pipeline paper
- [ ] MiST DB | 2020 paper mentions this | 2024 version doesn't!
- [ ] COGNAT: a web server for comparative analysis of genomic neighborhoods | Klimchuk et al., Biol. Direct 2020
- [ ] Systematic prediction of functionally linked genes in bacterial and archaeal genomes | Shmakov et al., Nat Protocols 2020
- [ ] Gene Graphics | Harrison et al., Bioinformatics 2018
- [ ] Conserved Genomic Neighborhood ... | Esch et al., BMC Bioinformatics 2020
- [ ] `gggenomes`: https://thackl.github.io/gggenomes
- [ ] `GeCoViz`: https://gecoviz.cgmlab.org | [paper](https://academic.oup.com/nar/article/50/W1/W352/6593547)
- [ ] @epbrenner: please add other papers from your list too

**Comment by daud99** [comment]
@jananiravi Can you assigned this task to me. I'm an Outreachy applicant selected for this session?
