### ISSUE TITLE
[FEAT] Add error handling for functions

### ISSUE THREAD

**Issue by Seyi007** [JRaviLab/MolEvolvR#30]
**Requirements**
- Ensure that all inputs are validated before processing. If inputs are invalid, return a user-friendly error message.
- Implement try-catch blocks where appropriate to handle exceptions gracefully without crashing the application.
- Update the documentation to include information about the new error-handling behavior

**Acceptance Criteria**
- [ ] All inputs are validated, and error messages are clear and informative.
- [ ]  Exceptions are caught and logged appropriately without crashing the application.
- [ ]  Documentation is updated to reflect the changes made.

**Comment by Seyi007** [comment]
Hi @jananiravi, issues #29 and this has been created as requested.

**Comment by Klangina** [comment]
@jananiravi can I kindly be assigned this task?

**Comment by jananiravi** [comment]
Sure! Can you post a note about which files/functions you're starting with so that others can contribute in parallel, too? Thanks!

**Comment by Seyi007** [comment]
Hi @Klangina, I'm creating the error handling mechanism on the R/acc2lin.R file. However, if you have started working on this, please leave a message so I can work on a different file.

**Comment by Seyi007** [comment]
Error handling done for R/acc2lin.R file.

**Comment by Seyi007** [comment]
Error handling and function names update is done for R/assign_job_queue.R file @jananiravi

**Comment by Seyi007** [comment]
Hi @awasyn, kindly drop updates on the files you're working on to avoid duplicating the same thing.

**Comment by awasyn** [comment]
Hey @Seyi007 .  I added input  checks for tree, summarize, reverse_operons and pre-msa-tree.
I am currently working on unit tests since it has less action and is isolated. I have  dependent PRs for  `fa2domain`, `cleanup`.

**Comment by Seyi007** [comment]
Okay @awasyn , well done! I'm currently working on the error handling for R/blastWrappers.R

**Comment by Seyi007** [comment]
Error handling for functions in R/blastWrappers.R is done, with pr #76
