### ISSUE TITLE
Rename the listed function names in R/acc2lin.R

### ISSUE THREAD

**Issue by Seyi007** [JRaviLab/MolEvolvR#35]
[R/acc2lin.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/acc2lin.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
| sink.reset | sinkReset |   |
| add_lins| addLineage |   |
| acc2lin| acc2Lineage |   |
| efetch_ipg| efetchIPG |   |
| ipg2lin| IPG2Lineage |   |

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/7#issuecomment-2394793279_
    
All update should follow this format: 
| Original          | Modified       | User Facing |
|-------------------|----------------|-------------|
| original_function | newFunction    | ✅          |

NOTE: Before beginning to work on a particular file, please check to see that @jananiravi has given the 👍 on the comment.

Please follow the [contributing guidelines](https://github.com/JRaviLab/MolEvolvR/blob/main/.github/CONTRIBUTING.md) and create a new branch containing your changes. Commit your work, and submit a PR when ready for review.

Additionally, use the search in all files functionality in VS code, Rstudio, or any other text editor, and list all files the function is being called or used to be updated later.

**Comment by awasyn** [comment]
Can i work on this?

**Comment by jananiravi** [comment]
made minor changes. Yes, go for it, @awasyn!

**Comment by awasyn** [comment]
I would like to suggest that we deprecate the functions and display update message instead of simply renaming them. I am assuming that these are functions already in use by user.  @jananiravi

**Comment by jananiravi** [comment]
This is a great suggestion in general, @awasyn! In this particular case, the repo is brand new and the only users are you (outreachy) and us! It's yet to go into widespread use. So for this instance, we plan to force-change the names and move on from there. In the future, once the package is in public use, depracation is the right way to go!
cc: @the-mayer
