### ISSUE TITLE
Rename functions in R/CHANGED-pre-msa-tree.R file

### ISSUE THREAD

**Issue by Seyi007** [JRaviLab/MolEvolvR#37]
[R/CHANGED-pre-msa-tree.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/CHANGED-pre-msa-tree.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
| convert_aln2fa | convertAlignment2FA | |
| to_titlecase | convert2TitleCase | |
| add_leaves | addLeaves2Alignment | |
| generate_all_aln2fa | generateAllAlignments2FA | |
| convert_aln2tsv | convertAlignment2TSV | |
| convert_accnum2fa | convertAccNum2FA | |
| add_name | addName | |
| map_acc2name | mapAcc2Name | |
| rename_fasta | renameFA | |
| acc2fa | acc2FA | |

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/7#issuecomment-2394795045_
            
All update should follow this format: 
| Original          | Modified       | User Facing |
|-------------------|----------------|-------------|
| original_function | newFunction    | ✅          |

NOTE: Before beginning to work on a particular file, please check to see that @jananiravi has given the 👍 on the comment.

Please follow the [contributing guidelines](https://github.com/JRaviLab/MolEvolvR/blob/main/.github/CONTRIBUTING.md) and create a new branch containing your changes. Commit your work, and submit a PR when ready for review.

Additionally, use the search in all files functionality in VS code, Rstudio, or any other text editor, and list all files the function is being called or used to be updated later.

**Comment by teddyCodex** [comment]
Hi @jananiravi @Seyi007 Please assign to me as well.

**Comment by jananiravi** [comment]
@teddyCodex @Seyi007, again, make sure you're using the updated names from #7.

**Comment by teddyCodex** [comment]
@Seyi007 I wasn't sure whether to commit the file containing the other occurrences of the function names, so I have attached the list here.
Please let me know if you'd rather have me commit them as part of the repo.
[function_occurrences.txt](https://github.com/user-attachments/files/17270179/function_occurrences.txt)

**Comment by the-mayer** [comment]
Fixed w #57
