### ISSUE TITLE
Rename function names in R/cleanup.R file

### ISSUE THREAD

**Issue by Seyi007** [JRaviLab/MolEvolvR#38]
[R/cleanup.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/cleanup.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
| clean_string | cleanString | |
| string2accnum | extractAccessionNumber | |
| make_accnums_unique | ensureUniqueAccessionNumbers | |
| cleanup_fasta_header | cleanFAHeaders | |
| remove_empty | removeEmptyRows | |
| repeat2s | condenseRepeatedDomains | |
| replaceQMs | replaceQuestionMarks | |
| remove_astrk | removeAsterisks | |
| remove_tails | removeTails | |
| cleanup_species | cleanSpecies | |
| cleanup_clust | cleanClusters | |
| cleanup_domarch | cleanDomainArchitecture | |
| cleanup_gencontext | cleanGenomicContext | |
| cleanup_GeneDesc | cleanGeneDescription | |
| pick_longer_duplicate | selectLongestDuplicate | |
| cleanup_lineage | cleanLineage | |

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/7#issuecomment-2394796056_
            
All updates should follow this format: 
| Original          | Modified       | User Facing |
|-------------------|----------------|-------------|
| original_function | newFunction    | ✅          |

NOTE: Before beginning to work on a particular file, please check to see that @jananiravi has given the 👍 on the comment.

Please follow the [contributing guidelines](https://github.com/JRaviLab/MolEvolvR/blob/main/.github/CONTRIBUTING.md) and create a new branch containing your changes. Commit your work, and submit a PR when ready for review.

Additionally, use the search in all files functionality in VS code, Rstudio, or any other text editor, and list all files the function is being called or used to be updated later.

**Comment by teddyCodex** [comment]
Hi @jananiravi @Seyi007 Can you assign this to me?

**Comment by jananiravi** [comment]
@teddyCodex @Seyi007, please use the updated names from #7.
