### ISSUE TITLE
Rename the listed function names in the following files.

### ISSUE THREAD

**Issue by Seyi007** [JRaviLab/MolEvolvR#44]
[R/combine_analysis.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/combine_analysis.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
|combine_full | combineFullAnalysis|  ✅ |
|combine_ipr | combineIPR|  ✅ |

[R/combine_analysis.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/combine_files.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
| combine_files | combineFiles |  ✅|

[R/create_lineage_lookup.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/create_lineage_lookup.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
|create_lineage_lookup | createLineageLookup| ✅ |
|shorten_NA | shortenNA| ❌  |

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/7#issuecomment-2395119886_

All updates should follow this format: 
| Original          | Modified       | User Facing |
|-------------------|----------------|-------------|
| original_function | newFunction    | ✅          |

NOTE: Before beginning to work on a particular file, please check to see that @jananiravi has given the 👍 on the comment.

Please follow the [contributing guidelines](https://github.com/JRaviLab/MolEvolvR/blob/main/.github/CONTRIBUTING.md) and create a new branch containing your changes. Commit your work, and submit a PR when ready for review.

Additionally, use the search in all files functionality in VS code, Rstudio, or any other text editor, and list all files the function is being called or used to be updated later.

**Comment by Seyi007** [comment]
Task done!

R/combine_analysis.R

                       files found:
combine_full | Namespace, .Rd(auto-gen)
combine_ipr  | Namespace, .Rd

R/combine_files.R
combine_files | Namespace, combine_analysis.R, .Rd

R/create_lineage_lookup.R
create_lineage_lookup | Namespace, GCA2lin.Rd, ipg2lin.Rd, acc2lin.R, lineage.R	
shorten_NA            | none (internal facing), prefixed with "."

**Comment by jananiravi** [comment]
@rlesiyon, please check how your createLineageLookup does compared to this function, please?

**Comment by Seyi007** [comment]
Hi @jananiravi , this task has been done as stated earlier, It was included in my recent pull request.

**Comment by the-mayer** [comment]
@Seyi007, I'm not seeing a PR for this. Could you please confirm that the PR was created or link the PR to this issue? Thank you!

**Comment by Seyi007** [comment]
I included in the same PR as the error handling functionality in this #76
