### ISSUE TITLE
Replace the function names in R/plotme.R

### ISSUE THREAD

**Issue by Seyi007** [JRaviLab/MolEvolvR#50]
[R/plotme.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/plotme.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
|count_to_sunburst | plotSunburst|
|count_to_treemap | plotTreemap|
|create_all_col_params | prepareColumnParams|
|create_one_col_params | prepareSingleColumnParams|
|assert_count_df | validateCountDF|
|all_non_n_cols_to_char | .all_non_n_cols_to_char | ✔️  |

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/7#issuecomment-2395215829_

All updates should follow this format: 
| Original          | Modified       | User Facing |
|-------------------|----------------|-------------|
| original_function | newFunction    | ✅          |

NOTE: Before beginning to work on a particular file, please check to see that @jananiravi has given the 👍 on the comment.

Please follow the [contributing guidelines](https://github.com/JRaviLab/MolEvolvR/blob/main/.github/CONTRIBUTING.md) and create a new branch containing your changes. Commit your work, and submit a PR when ready for review.

Additionally, use the search in all files functionality in VS code, Rstudio, or any other text editor, and list all files the function is being called or used to be updated later.

**Comment by jananiravi** [comment]
#notetoself @the-mayer, we need to figure out what these `prepareXYZ` functions are doing. The function names seem a bit vague.

**Comment by teddyCodex** [comment]
> #notetoself @the-mayer, we need to figure out what these `prepareXYZ` functions are doing. The function names seem a bit vague.

Not sure if this is helpful @jananiravi but all these functions appear to be user-facing. They all appear in the NAMESPACE file.

create_all_col_params - appears to be designed to generate a set of parameters based on the columns in a data frame (count_data)
create_one_col_params - appears to processes a specific column (col_num) in a data frame (df) to generate parameters such as ids, parents, labels, values, and hovertext.

**Comment by the-mayer** [comment]
Just a note, eventually we will be reducing the number of exports for MolEvolvR.
Currently, it exports more functions than a user will be expected to use. _Eventually_ this will be tackled in another series of issues.

At current, the NAMESPACE file is not the definitive source of truth for what will be exported in the release version of MolEvolvR .
