### ISSUE TITLE
Replace the function names in R/plotting.R

### ISSUE THREAD

**Issue by Seyi007** [JRaviLab/MolEvolvR#51]
[R/plotting.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/plotting.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
| shorten_lineage | shortenLineage| |
| upset.plot | plotUpSet| |
| lineage.DA.plot | plotLineageDA| |
| lineage.Query.plot | plotLineageQuery| |
| lineage.neighbors.plot | plotLineageNeighbors| |
| lineage.domain_repeats.plot | plotLineageDomainRepeats| |
| LineagePlot | plotLineageHeatmap| |
| LevelReduction | .LevelReduction| |
| GetKingdom | .GetKingdom| |
| stacked_lin_plot | plotStackedLineage| |
| Wordcloud3 | plotWordcloud3| |
| wordcloud_element | createWordCloudElement| |
| wordcloud2_element | createWordCloud2Element| |
| lineage_sunburst | plotLineageSunburst| |
| lineage.plot* | plotLineage| |
* perhaps a duplicate?

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/7#issuecomment-2395216713_

All updates should follow this format: 
| Original          | Modified       | User Facing |
|-------------------|----------------|-------------|
| original_function | newFunction    | ✅          |

NOTE: Before beginning to work on a particular file, please check to see that @jananiravi has given the 👍 on the comment.

Please follow the [contributing guidelines](https://github.com/JRaviLab/MolEvolvR/blob/main/.github/CONTRIBUTING.md) and create a new branch containing your changes. Commit your work, and submit a PR when ready for review.

Additionally, use the search in all files functionality in VS code, Rstudio, or any other text editor, and list all files the function is being called or used to be updated later.

**Comment by jananiravi** [comment]
made minor modifications. good to go.
