### ISSUE TITLE
Replace the function names in listed files

### ISSUE THREAD

**Issue by Seyi007** [JRaviLab/MolEvolvR#52]
[R/pre-msa-tree.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/pre-msa-tree.R)

[R/CHANGED-pre-msa-tree.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/CHANGED-pre-msa-tree.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
RepresentativeAccNums | createRepresentativeAccessionNumbers |
write.MsaAAMultipleAlignment | writeMsaAaMultipleAlignment2FA |
get_accnums_from_fasta_file | getAccessionNumbersFromFA |

[R/reverse_operons.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/reverse_operons.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
| reveql | straightenOperonSeq |
| reverse_operon | reverseOperonSeq |

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/7#issuecomment-2395218070_

All updates should follow this format: 
| Original          | Modified       | User Facing |
|-------------------|----------------|-------------|
| original_function | newFunction    | ✅          |

NOTE: Before beginning to work on a particular file, please check to see that @jananiravi has given the 👍 on the comment.

Please follow the [contributing guidelines](https://github.com/JRaviLab/MolEvolvR/blob/main/.github/CONTRIBUTING.md) and create a new branch containing your changes. Commit your work, and submit a PR when ready for review.

Additionally, use the search in all files functionality in VS code, Rstudio, or any other text editor, and list all files the function is being called or used to be updated later.

**Comment by jananiravi** [comment]
These need to be renamed from the original list #7, as well. E.g., AccessionNumbers to AccNum. MSA -- all caps, etc.

**Comment by teddyCodex** [comment]
> These need to be renamed from the original list #7, as well. E.g., AccessionNumbers to AccNum. MSA -- all caps, etc.

Hi @jananiravi this name `writeMSAAAMultipleAlignment2FA` doesn't seem very intuitive especially cos of the 'AAA'
Any suggestions for a better name?
cc @the-mayer 
does `writeMSA_AAMultipleAlignment2FA` work?

**Comment by jananiravi** [comment]
writeMSA_AA2FA should, in fact, suffice, I think. [could you double-check to see that's what the function does?]
cc: @epbrenner
