### ISSUE TITLE
Replace the function names in R/summarize.R

### ISSUE THREAD

**Issue by Seyi007** [JRaviLab/MolEvolvR#53]
[R/summarize.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/summarize.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
| filter_by_doms | filterByDomains| 
| count_bycol | countByColumn| |
| elements2words | elements2Words| |
| find_paralogs | findParalogs | |
| words2wc | words2WordCounts| |
| filter_freq | filterByFrequency| |
| summarize_bylin | summarizeByLineage| |
| summ.DA.byLin | summarizeDomainArch_ByLineage| |
| summ.DA | summarizeDomainArch|
| summ.GC.byDALin | summarizeGenomicContext_ByDomainArchAndLineage| |
| summ.GC.byLin | summarizeGenomicContext_ByLineage| |
| summ.GC | summarizeGenomicContext| |
| total_counts | totalGenomicOrDomainArchitectureCounts| |

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/7#issuecomment-2395219549_

All updates should follow this format: 
| Original          | Modified       | User Facing |
|-------------------|----------------|-------------|
| original_function | newFunction    | ✅          |

NOTE: Before beginning to work on a particular file, please check to see that @jananiravi has given the 👍 on the comment.

Please follow the [contributing guidelines](https://github.com/JRaviLab/MolEvolvR/blob/main/.github/CONTRIBUTING.md) and create a new branch containing your changes. Commit your work, and submit a PR when ready for review.

Additionally, use the search in all files functionality in VS code, Rstudio, or any other text editor, and list all files the function is being called or used to be updated later.

**Comment by teddyCodex** [comment]
@jananiravi okay to go ahead with this?
