### ISSUE TITLE
Replace the function names in R/tree.R

### ISSUE THREAD

**Issue by Seyi007** [JRaviLab/MolEvolvR#54]
[R/tree.R](https://github.com/JRaviLab/MolEvolvR/blob/main/R/tree.R)
| **Original** | **Modified** | **User Facing** |
|--------|--------|--------|
|convert_fa2tre | convertFA2Tree | |
|generate_trees | convertAlignment2Trees | |
|generate_fa2tre | convertFA2Tree | |

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/7#issuecomment-2395220032_

All updates should follow this format: 
| Original          | Modified       | User Facing |
|-------------------|----------------|-------------|
| original_function | newFunction    | ✅          |

NOTE: Before beginning to work on a particular file, please check to see that @jananiravi has given the 👍 on the comment.

Please follow the [contributing guidelines](https://github.com/JRaviLab/MolEvolvR/blob/main/.github/CONTRIBUTING.md) and create a new branch containing your changes. Commit your work, and submit a PR when ready for review.

Additionally, use the search in all files functionality in VS code, Rstudio, or any other text editor, and list all files the function is being called or used to be updated later.

**Comment by teddyCodex** [comment]
@jananiravi okay to go ahead with this?

**Comment by jananiravi** [comment]
made minor modifications -- go ahead.

**Comment by teddyCodex** [comment]
@jananiravi You edit above has:

convert_fa2tre --> convertFA2Tree
generate_fa2tre --> convertFA2Tree

is this intentional?
using createFA2Tree pending your response.

**Comment by jananiravi** [comment]
good catch -- intentional because they should have that name but creating duplicate names was not intentional! They both do the same thing (takes `fasta` sequences and generates `trees`, but use different algorithms -- that needs to be clarified. Also, I'm not sure which one is in use. Could you check, @the-mayer @epbrenner & recommend accordingly?
