### ISSUE TITLE
Refactor internal functions to be defined outside of plot functions

### ISSUE THREAD

**Issue by the-mayer** [JRaviLab/MolEvolvR#80]
Tagging functions for future review. 

The following internal functions should be defined outside of the plotting functions that currently use them. This way, the plot functions can reference these external functions, avoiding the need to define functions within functions.

- `.LevelReduction()`
- `.GetKingdom()`

_Originally posted by @the-mayer in https://github.com/JRaviLab/MolEvolvR/issues/63#issuecomment-2400073453_

**Comment by teddyCodex** [comment]
taking a crack at this @the-mayer

**Comment by Joiejoie1** [comment]
@teddyCodex are you working on this or can I give it a shot as well?

**Comment by teddyCodex** [comment]
Hi @Joiejoie1 Already raised a PR
Waiting on @the-mayer to review.
